# Generated by Django 5.0.2 on 2024-07-06 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidates',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TestName', models.CharField(max_length=100)),
                ('total_questions', models.IntegerField(blank=True, null=True)),
                ('test_description', models.TextField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question', models.TextField()),
                ('Op1', models.CharField(max_length=100)),
                ('Op2', models.CharField(max_length=100)),
                ('Op3', models.CharField(max_length=100)),
                ('Op4', models.CharField(max_length=100)),
                ('rightAns', models.CharField(max_length=100)),
                ('TestName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OTSapp.test')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('right', models.IntegerField()),
                ('wrong', models.IntegerField()),
                ('point', models.IntegerField()),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OTSapp.candidates')),
                ('TestName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OTSapp.test')),
            ],
            options={
                'unique_together': {('username', 'TestName')},
            },
        ),
    ]
